spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:ecommerce_db}
    username: ${POSTGRES_USER:ecommerce}
    password: ${POSTGRES_PASSWORD:ecommerce}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
